### ISSUE TITLE
最新的 15.05 正式版 LED设置问题

### ISSUE THREAD

**Issue by shao222** [NemoAlex/openwrt-wrt1900ac-docs#1]
貌似只提供了 2个LED 
1power 2esata  

lan灯一直不亮。 有人遇到吗？

**Comment by NemoAlex** [comment]
没有注意过。我这里 Wifi 的灯是正常的。

**Comment by shao222** [comment]
你在这里回复真快。大概是我升级安装的问题。

我能不能重新刷一次完整的15.05 包？

就是这个：openwrt-15.05-mvebu-armada-385-linksys-cobra-squashfs-factory.img ？

**Comment by NemoAlex** [comment]
可以的，刷回原厂再刷过来。

**Comment by shao222** [comment]
不能直接在openwrt 刷一次吗？

**Comment by NemoAlex** [comment]
也可以。刷那个 tar 文件，选择不保存配置。

**Comment by shao222** [comment]
哦 对 不保存配置。 好的 。我明天再试试看。谢谢！

**Comment by shao222** [comment]
对了 btw shadowsocks 更新了。
