### ISSUE TITLE
5G无信号

### ISSUE THREAD

**Issue by jamesvip** [NemoAlex/openwrt-wrt1900ac-docs#12]
从1.1 升级到1.2， 型号是v2版本路由，5G始终无信号

**Comment by NemoAlex** [comment]
试试不要保留配置，重新刷一次。

**Comment by jamesvip** [comment]
谢谢，重新不保留配置刷入，现在好了，请教一个问题，如果在路由开vpn让iphone在4G网络连路由走dns和ss，试了open connect，dns必须要指定，又没有wrt1900 v2 的pptp服务包，openwrt貌似还不支持ios，有没有什么好建议，另外就是openwrt的ss能更新成ssr吗？

**Comment by NemoAlex** [comment]
1. 没有看懂第一个问题，你的意思是路由器开一个 PPTP 服务端，手机从外网连过去？如果有公网 IP，是比较可行的。可以安装 PPTP 的服务端。教程很多。
2. 我认为目前没有多少必要使用 SSR，尤其是在新版已经修补了暴露特征的漏洞的情况下。你喜欢的话可以自己编译安装。编译的教程在本项目 wiki 里有。
