### ISSUE TITLE
openwrt 自带的 transmission v2.84 貌似某PT不支持。

### ISSUE THREAD

**Issue by shao222** [NemoAlex/openwrt-wrt1900ac-docs#14]
@NemoAlex  能不能编译一个低版本的提供使用呢。

**Comment by NemoAlex** [comment]
我不记得有没有办法改 Transmission 的 user agent，让自己看起来是低版本的。如果有这个选项就好了。
另外你其实可以用 aria2，可以改 user agent，想要什么版本都行。

**Comment by shao222** [comment]
aria2 这么神奇？ 一直听说，从未尝试。

今天去试试看。谢！

**Comment by NemoAlex** [comment]
推荐看这篇文章：
https://www.librehat.com/aria2-camouflage-utorrent-pt-download/
Web UI 可以用 YAAW 或者 webui-aria2
另外我自己也在写一个，还不算特别完善，有兴趣的话可以去看看。

**Comment by NemoAlex** [comment]
需要注意的是官方源里的 aria2 编译，是没有加入 BT 功能的，Nemo 1.2 中自带的 aria2 已经加入了 BT 功能。不过这个版本的 SSL 有点问题，有些 PT 的 Tracker 是 https 的，就会出错。选项里加入 check-certificate=false 就好了。
这两天我会发布 Nemo 1.3，基于 15.05.1，同时修复了这个问题。

**Comment by shao222** [comment]
好吧 看上去还不能简单使用了。等你的 1.3吧。
NemoAlex notifications@github.com于2016年3月30日 周三10:40写道：

**Comment by shao222** [comment]
听说这个aria2 webui 不错。
https://github.com/ziahamza/webui-aria2
