### ISSUE TITLE
你好, 交叉编译IPK的时候是否需要配置完整的buildroot?

### ISSUE THREAD

**Issue by GF-Huang** [NemoAlex/openwrt-wrt1900ac-docs#15]
我在vps上编译 shadowsocks-libev 的时候遇到错误, 怀疑是否需要下载完整的 OpenWrt 的源码配置 feeds等操作? 
还是说下载官网上已经编译的好的SDK包就行?
麻烦大神指导下.
![image](https://cloud.githubusercontent.com/assets/4510984/14224973/8b2a3550-f8e4-11e5-9c09-414d8e2e1d0a.png)

**Comment by NemoAlex** [comment]
用 SDK 就可以编译。
我重新测试了一下，这样操作来编译 github.com/shadowsocks/openwrt-shadowsocks 是没有问题的。
是不是 clone 项目出了问题？
