### ISSUE TITLE
可以编译个ssR-libev-full 吗？

### ISSUE THREAD

**Issue by shao222** [NemoAlex/openwrt-wrt1900ac-docs#22]
https://github.com/bettermanbao/openwrt-shadowsocksR-libev-full

@NemoAlex 

Thanks! 

可惜我不会编译。

**Comment by NemoAlex** [comment]
我个人对这个项目没有多大兴趣，而且最近比较没有空。
可能会在有空的时候看一下。
抱歉了。

**Comment by shao222** [comment]
没关系 这个不急 以后再说。
NemoAlex notifications@github.com于2016年5月31日 周二09:34写道：
