### ISSUE TITLE
Flash 空间问题

### ISSUE THREAD

**Issue by HugoPresents** [NemoAlex/openwrt-wrt1900ac-docs#23]
为啥我根目录只有这么点儿，大量都在 /tmp 目录，刷的官方固件
![image](https://cloud.githubusercontent.com/assets/1559200/15750100/ad72b926-2917-11e6-91bb-14c82f9e74a0.png)

**Comment by NemoAlex** [comment]
OpenWrt 的设计就是这样的。

**Comment by HugoPresents** [comment]
软件安装目录好像是 根目录？ 那不是再装几个就没空间了

**Comment by HugoPresents** [comment]
看了官方的 wiki nand 的 128M 被分割成了三大块 每个 40m 左右，其中两个分区用来装系统了，双系统。所以留给 opkg 的空间只有 30M 不到了，准备搞个 U盘来给路由器扩容，谢谢回复！
