### ISSUE TITLE
有空支持一下多线多拨和单线多拨吗

### ISSUE THREAD

**Issue by griffinqiu** [NemoAlex/openwrt-wrt1900ac-docs#26]
随着移动大力推广宽带, 很多人都可以免费获得移动20M宽带.
我就同时拉了移动和电信宽带. 原打算在WRT1900AC上多线多拨.
发现一些问题:
1. 怎么样把一个LAN变成WAN
2. WRT1900AC 固件多拨有点问题. 具体变现为当第二个PPPOE拨号后第一个PPPOE会断网.

**Comment by griffinqiu** [comment]
电信升级到200M了 已经不需要多拨了....

**Comment by NemoAlex** [comment]
Orz...最近事情太多，有点对不住
