### ISSUE TITLE
这个脚本可以收录一下。

### ISSUE THREAD

**Issue by shao222** [NemoAlex/openwrt-wrt1900ac-docs#5]
OpenWRT 自动更新软件包脚本
https://cokebar.info/archives/930

**Comment by shao222** [comment]
好像有问题。

**Comment by NemoAlex** [comment]
这种事情自动来做，有点太草率了吧

**Comment by shao222** [comment]
我试了 不好用导致我重装luci base 才进web。

NemoAlex notifications@github.com于2015年10月4日 周日18:43写道：
