### ISSUE TITLE
Can't install mwlwifi

### ISSUE THREAD

**Issue by noooonee** [NemoAlex/openwrt-wrt1900ac-docs#6]
Maybe something wrong with this prebuilt package?

[root@OpenWrt:~# opkg install kmod-mwlwifi_3.18.20+10.3.0.14-20151130-1_mvebu.ipk 
Not downgrading package kmod-mwlwifi on root from 3.18.20+10.3.0.141-20151125-1 to 3.18.20+10.3.0.14-20151130-1.

**Comment by noooonee** [comment]
I'm using 1900ac v2, thanks.

**Comment by NemoAlex** [comment]
Sorry this was my fault. In the last version I used version number "10.3.0.141", which is higher then 10.3.0.14.
So you need to use `opkg install --force-downgrade` to install the package.

**Comment by noooonee** [comment]
It works, good job!
